-- ============================================================================
-- Heidelberger Schloss, Phase 10: Tabellen mit dem Praefix HEI_ im Schema DEMO
-- Aufbau nach deinen SEM_-Tabellen (Semiramis): Praefix je Projekt, <TABELLE>_ID,
-- _PK / _UK / _FK / _CK je Tabelle. Jede Anweisung endet mit einer Zeile "/".
-- Das Skript kann mehrfach laufen: was es schon gibt, meldet der Einrichter als "vorhanden".
-- Reihenfolge: 01 Tabellen, 02 Folgen, Trigger, Indizes, 03 Paket HEI_API, 04 Grunddaten.
-- Zeichensatz: UTF-8.
-- ============================================================================

CREATE TABLE HEI_SOURCE (
  SOURCE_ID       NUMBER(10)     NOT NULL,
  CODE            VARCHAR2(30)   NOT NULL,
  AUTOR           VARCHAR2(80)   NOT NULL,
  LEBENSZEIT      VARCHAR2(60),
  WERK            VARCHAR2(160)  NOT NULL,
  STELLE          VARCHAR2(40),
  SPRACHE         VARCHAR2(40),
  UEBERLIEFERUNG  VARCHAR2(200),
  ABSTAND_JAHRE   NUMBER(5),
  BEZUG           VARCHAR2(10),
  KERNAUSSAGE     VARCHAR2(1000) NOT NULL,
  MASSE           VARCHAR2(400),
  BELEG           VARCHAR2(400),
  CONSTRAINT HEI_SOURCE_PK PRIMARY KEY (SOURCE_ID),
  CONSTRAINT HEI_SOURCE_UK UNIQUE (CODE)
)
/

CREATE TABLE HEI_STAGE (
  STAGE_ID        NUMBER(10)     NOT NULL,
  NR              NUMBER(2)      NOT NULL,
  JAHR            NUMBER(4)      NOT NULL,
  DATUM           DATE,
  NAME            VARCHAR2(60)   NOT NULL,
  KURZ            VARCHAR2(160)  NOT NULL,
  BESCHREIBUNG    VARCHAR2(1000),
  SOURCE_ID       NUMBER(10),
  CONSTRAINT HEI_STAGE_PK PRIMARY KEY (STAGE_ID),
  CONSTRAINT HEI_STAGE_UK UNIQUE (NR),
  CONSTRAINT HEI_STAGE_NR_CK CHECK (NR BETWEEN 0 AND 3),
  CONSTRAINT HEI_STAGE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES HEI_SOURCE (SOURCE_ID)
)
/

CREATE TABLE HEI_BUILDING (
  BUILDING_ID     NUMBER(10)     NOT NULL,
  CODE            VARCHAR2(30)   NOT NULL,
  NAME            VARCHAR2(80)   NOT NULL,
  NAME_HISTORISCH VARCHAR2(80),
  BEZUG           VARCHAR2(10)   NOT NULL,
  DETAIL          VARCHAR2(10)   NOT NULL,
  STUFEN          NUMBER(2)      DEFAULT 15 NOT NULL,
  ROLLE           VARCHAR2(400),
  X_M             NUMBER(9,2),
  Z_M             NUMBER(9,2),
  GEOM            SDO_GEOMETRY,
  SOURCE_ID       NUMBER(10),
  CONSTRAINT HEI_BUILDING_PK PRIMARY KEY (BUILDING_ID),
  CONSTRAINT HEI_BUILDING_UK UNIQUE (CODE),
  CONSTRAINT HEI_BUILDING_DETAIL_CK CHECK (DETAIL IN ('VOLL','MITTEL','EINFACH')),
  CONSTRAINT HEI_BUILDING_STUFEN_CK CHECK (STUFEN BETWEEN 0 AND 15),
  CONSTRAINT HEI_BUILDING_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES HEI_SOURCE (SOURCE_ID)
)
/

CREATE TABLE HEI_CHRONIK (
  CHRONIK_ID      NUMBER(10)     NOT NULL,
  STAGE_ID        NUMBER(10)     NOT NULL,
  JAHR            NUMBER(4)      NOT NULL,
  DATUM           DATE,
  TITEL           VARCHAR2(80)   NOT NULL,
  TEXT            VARCHAR2(600)  NOT NULL,
  SOURCE_ID       NUMBER(10),
  CONSTRAINT HEI_CHRONIK_PK PRIMARY KEY (CHRONIK_ID),
  CONSTRAINT HEI_CHRONIK_UK UNIQUE (JAHR, TITEL),
  CONSTRAINT HEI_CHRONIK_STAGE_FK FOREIGN KEY (STAGE_ID) REFERENCES HEI_STAGE (STAGE_ID),
  CONSTRAINT HEI_CHRONIK_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES HEI_SOURCE (SOURCE_ID)
)
/

CREATE TABLE HEI_VIEW (
  VIEW_ID         NUMBER(10)     NOT NULL,
  NR              NUMBER(3)      NOT NULL,
  NAME            VARCHAR2(60)   NOT NULL,
  NOTIZ           VARCHAR2(200),
  DREHPUNKT_X     NUMBER(9,2)    NOT NULL,
  DREHPUNKT_Z     NUMBER(9,2)    NOT NULL,
  HOEHE_UEBER_BODEN NUMBER(8,2)  NOT NULL,
  GIER_GRAD       NUMBER(8,2)    NOT NULL,
  NICK_GRAD       NUMBER(6,2)    NOT NULL,
  ABSTAND_M       NUMBER(8,2)    NOT NULL,
  INNEN           CHAR(1)        DEFAULT 'N' NOT NULL,
  CONSTRAINT HEI_VIEW_PK PRIMARY KEY (VIEW_ID),
  CONSTRAINT HEI_VIEW_UK UNIQUE (NR),
  CONSTRAINT HEI_VIEW_INNEN_CK CHECK (INNEN IN ('J','N'))
)
/

CREATE TABLE HEI_CLIP (
  CLIP_ID         NUMBER(10)     NOT NULL,
  CODE            VARCHAR2(30)   NOT NULL,
  ART             VARCHAR2(10)   NOT NULL,
  STUFE           NUMBER(1)      DEFAULT 0 NOT NULL,
  NR              NUMBER(3),
  NAME            VARCHAR2(80)   NOT NULL,
  INFO            VARCHAR2(400),
  DAUER_S         NUMBER(7,2),
  CONSTRAINT HEI_CLIP_PK PRIMARY KEY (CLIP_ID),
  CONSTRAINT HEI_CLIP_UK UNIQUE (CODE),
  CONSTRAINT HEI_CLIP_ART_CK CHECK (ART IN ('FAHRT','DREHBUCH')),
  CONSTRAINT HEI_CLIP_STUFE_CK CHECK (STUFE BETWEEN 0 AND 3)
)
/

CREATE TABLE HEI_SHOT (
  SHOT_ID         NUMBER(10)     NOT NULL,
  CLIP_ID         NUMBER(10)     NOT NULL,
  NR              NUMBER(3)      NOT NULL,
  NAME            VARCHAR2(80)   NOT NULL,
  STUNDE_VON      NUMBER(5,2)    NOT NULL,
  STUNDE_BIS      NUMBER(5,2)    NOT NULL,
  NEBEL           CHAR(1)        DEFAULT 'N' NOT NULL,
  DUNST           NUMBER(4,2)    DEFAULT 0.12 NOT NULL,
  SOURCE_ID       NUMBER(10),
  CONSTRAINT HEI_SHOT_PK PRIMARY KEY (SHOT_ID),
  CONSTRAINT HEI_SHOT_UK UNIQUE (CLIP_ID, NR),
  CONSTRAINT HEI_SHOT_NEBEL_CK CHECK (NEBEL IN ('J','N')),
  CONSTRAINT HEI_SHOT_STUNDE_CK CHECK (STUNDE_VON BETWEEN 0 AND 24 AND STUNDE_BIS BETWEEN 0 AND 24),
  CONSTRAINT HEI_SHOT_CLIP_FK FOREIGN KEY (CLIP_ID) REFERENCES HEI_CLIP (CLIP_ID) ON DELETE CASCADE,
  CONSTRAINT HEI_SHOT_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES HEI_SOURCE (SOURCE_ID)
)
/

CREATE TABLE HEI_PANEL (
  PANEL_ID        NUMBER(10)     NOT NULL,
  SHOT_ID         NUMBER(10)     NOT NULL,
  VON_S           NUMBER(6,1)    NOT NULL,
  BIS_S           NUMBER(6,1)    NOT NULL,
  KOPF            VARCHAR2(80)   NOT NULL,
  TEXT            VARCHAR2(600)  NOT NULL,
  QUELLE_TEXT     VARCHAR2(200),
  SOURCE_ID       NUMBER(10),
  CONSTRAINT HEI_PANEL_PK PRIMARY KEY (PANEL_ID),
  CONSTRAINT HEI_PANEL_UK UNIQUE (SHOT_ID, VON_S),
  CONSTRAINT HEI_PANEL_ZEIT_CK CHECK (BIS_S > VON_S),
  CONSTRAINT HEI_PANEL_SHOT_FK FOREIGN KEY (SHOT_ID) REFERENCES HEI_SHOT (SHOT_ID) ON DELETE CASCADE,
  CONSTRAINT HEI_PANEL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES HEI_SOURCE (SOURCE_ID)
)
/

CREATE TABLE HEI_SESSION (
  SESSION_ID      NUMBER(10)     NOT NULL,
  GESTARTET       TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  BEENDET         TIMESTAMP(6),
  DAUER_S         NUMBER(8),
  RECHNER         VARCHAR2(80 CHAR),
  BENUTZER        VARCHAR2(60 CHAR),
  APP_VERSION     VARCHAR2(20 CHAR),
  JAVA_VERSION    VARCHAR2(40 CHAR),
  KERNE           NUMBER(3),
  SPEICHER_MAX_MB NUMBER(6),
  FENSTER_B       NUMBER(5),
  FENSTER_H       NUMBER(5),
  STUFE_START     NUMBER(1),
  ZUSTAND_GELADEN CHAR(1)        DEFAULT 'N' NOT NULL,
  BILDER_S        NUMBER(5,1),
  MS_BILD         NUMBER(6,1),
  SPEICHER_MB     NUMBER(6),
  CONSTRAINT HEI_SESSION_PK PRIMARY KEY (SESSION_ID),
  CONSTRAINT HEI_SESSION_GELADEN_CK CHECK (ZUSTAND_GELADEN IN ('J','N'))
)
/

CREATE TABLE HEI_STATE (
  STATE_ID        NUMBER(10)     NOT NULL,
  NAME            VARCHAR2(60 CHAR)   NOT NULL,
  ART             VARCHAR2(8)    NOT NULL,
  GESPEICHERT     TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  SESSION_ID      NUMBER(10),
  STUFE            NUMBER(1)      DEFAULT 0 NOT NULL,
  TAG              NUMBER(3)      DEFAULT 172 NOT NULL,
  STUNDE           NUMBER(5,2)    DEFAULT 16 NOT NULL,
  ZEITRAFFER       NUMBER(4,2)    DEFAULT 0 NOT NULL,
  WETTER           NUMBER(2)      DEFAULT 0 NOT NULL,
  DUNST            NUMBER(3)      DEFAULT 12 NOT NULL,
  NEBEL            NUMBER(3)      DEFAULT 100 NOT NULL,
  TALNEBEL         NUMBER(3)      DEFAULT 100 NOT NULL,
  NEBELTAG         CHAR(1)        DEFAULT 'N' NOT NULL,
  WIND             NUMBER(3)      DEFAULT 35 NOT NULL,
  FX_STRAHLEN      CHAR(1)        DEFAULT 'J' NOT NULL,
  FX_UEBERSTRAHLEN CHAR(1)        DEFAULT 'J' NOT NULL,
  FX_RAUCH         CHAR(1)        DEFAULT 'J' NOT NULL,
  FX_FACKELN       CHAR(1)        DEFAULT 'J' NOT NULL,
  FX_SCHAUER       CHAR(1)        DEFAULT 'N' NOT NULL,
  L_HOFSTAAT       CHAR(1)        DEFAULT 'J' NOT NULL,
  DICHTE_HOF       NUMBER(3)      DEFAULT 85 NOT NULL,
  L_REITER         CHAR(1)        DEFAULT 'J' NOT NULL,
  L_VOEGEL         CHAR(1)        DEFAULT 'J' NOT NULL,
  L_KERZEN         CHAR(1)        DEFAULT 'J' NOT NULL,
  BRUNNEN          CHAR(1)        DEFAULT 'J' NOT NULL,
  BRUNNEN_DICHTE   NUMBER(4)      DEFAULT 100 NOT NULL,
  Z_WASSERWEG      CHAR(1)        DEFAULT 'N' NOT NULL,
  Z_WASSERORGEL    CHAR(1)        DEFAULT 'J' NOT NULL,
  Z_KLANG          CHAR(1)        DEFAULT 'J' NOT NULL,
  Z_LUPE           CHAR(1)        DEFAULT 'N' NOT NULL,
  SCHNITT_NR       NUMBER(1)      DEFAULT 0 NOT NULL,
  Z_GEPLANT        CHAR(1)        DEFAULT 'J' NOT NULL,
  QUALITAET        VARCHAR2(4)    DEFAULT 'AUTO' NOT NULL,
  STIL             NUMBER(2)      DEFAULT 0 NOT NULL,
  RUNDFLUG         CHAR(1)        DEFAULT 'N' NOT NULL,
  BLICKPUNKT       NUMBER(3)      DEFAULT 0 NOT NULL,
  DREHPUNKT_X      NUMBER(9,2)    DEFAULT 0 NOT NULL,
  DREHPUNKT_Y      NUMBER(9,2)    DEFAULT 0 NOT NULL,
  DREHPUNKT_Z      NUMBER(9,2)    DEFAULT 0 NOT NULL,
  GIER_GRAD        NUMBER(8,2)    DEFAULT 0 NOT NULL,
  NICK_GRAD        NUMBER(6,2)    DEFAULT 0 NOT NULL,
  ABSTAND_M        NUMBER(8,2)    DEFAULT 100 NOT NULL,
  CONSTRAINT HEI_STATE_PK PRIMARY KEY (STATE_ID),
  CONSTRAINT HEI_STATE_ART_CK CHECK (ART IN ('AUTO','MANUELL')),
  CONSTRAINT HEI_STATE_SESSION_FK FOREIGN KEY (SESSION_ID) REFERENCES HEI_SESSION (SESSION_ID) ON DELETE SET NULL,
  CONSTRAINT HEI_STATE_STUFE_CK CHECK (STUFE BETWEEN 0 AND 3),
  CONSTRAINT HEI_STATE_TAG_CK CHECK (TAG BETWEEN 1 AND 366),
  CONSTRAINT HEI_STATE_STUNDE_CK CHECK (STUNDE BETWEEN 0 AND 24),
  CONSTRAINT HEI_STATE_DUNST_CK CHECK (DUNST BETWEEN 0 AND 100),
  CONSTRAINT HEI_STATE_NEBEL_CK CHECK (NEBEL BETWEEN 0 AND 200),
  CONSTRAINT HEI_STATE_TALNEBEL_CK CHECK (TALNEBEL BETWEEN 0 AND 200),
  CONSTRAINT HEI_STATE_NEBELTAG_CK CHECK (NEBELTAG IN ('J','N')),
  CONSTRAINT HEI_STATE_WIND_CK CHECK (WIND BETWEEN 0 AND 100),
  CONSTRAINT HEI_STATE_FX_STRAHLEN_CK CHECK (FX_STRAHLEN IN ('J','N')),
  CONSTRAINT HEI_STATE_FX_UEBERSTRAHLEN_CK CHECK (FX_UEBERSTRAHLEN IN ('J','N')),
  CONSTRAINT HEI_STATE_FX_RAUCH_CK CHECK (FX_RAUCH IN ('J','N')),
  CONSTRAINT HEI_STATE_FX_FACKELN_CK CHECK (FX_FACKELN IN ('J','N')),
  CONSTRAINT HEI_STATE_FX_SCHAUER_CK CHECK (FX_SCHAUER IN ('J','N')),
  CONSTRAINT HEI_STATE_L_HOFSTAAT_CK CHECK (L_HOFSTAAT IN ('J','N')),
  CONSTRAINT HEI_STATE_DICHTE_HOF_CK CHECK (DICHTE_HOF BETWEEN 0 AND 100),
  CONSTRAINT HEI_STATE_L_REITER_CK CHECK (L_REITER IN ('J','N')),
  CONSTRAINT HEI_STATE_L_VOEGEL_CK CHECK (L_VOEGEL IN ('J','N')),
  CONSTRAINT HEI_STATE_L_KERZEN_CK CHECK (L_KERZEN IN ('J','N')),
  CONSTRAINT HEI_STATE_BRUNNEN_CK CHECK (BRUNNEN IN ('J','N')),
  CONSTRAINT HEI_STATE_BRUNNEN_DICHTE_CK CHECK (BRUNNEN_DICHTE BETWEEN 10 AND 800),
  CONSTRAINT HEI_STATE_Z_WASSERWEG_CK CHECK (Z_WASSERWEG IN ('J','N')),
  CONSTRAINT HEI_STATE_Z_WASSERORGEL_CK CHECK (Z_WASSERORGEL IN ('J','N')),
  CONSTRAINT HEI_STATE_Z_KLANG_CK CHECK (Z_KLANG IN ('J','N')),
  CONSTRAINT HEI_STATE_Z_LUPE_CK CHECK (Z_LUPE IN ('J','N')),
  CONSTRAINT HEI_STATE_SCHNITT_NR_CK CHECK (SCHNITT_NR BETWEEN 0 AND 2),
  CONSTRAINT HEI_STATE_Z_GEPLANT_CK CHECK (Z_GEPLANT IN ('J','N')),
  CONSTRAINT HEI_STATE_QUALITAET_CK CHECK (QUALITAET IN ('AUTO','50','75','100')),
  CONSTRAINT HEI_STATE_RUNDFLUG_CK CHECK (RUNDFLUG IN ('J','N'))
)
/

CREATE TABLE HEI_EVENT (
  EVENT_ID        NUMBER(10)     NOT NULL,
  SESSION_ID      NUMBER(10)     NOT NULL,
  ZEIT            TIMESTAMP(6)   DEFAULT LOCALTIMESTAMP NOT NULL,
  SEKUNDE         NUMBER(8,1)    NOT NULL,
  ART             VARCHAR2(12)   NOT NULL,
  ZIEL            VARCHAR2(80 CHAR),
  WERT            VARCHAR2(200 CHAR),
  STUFE           NUMBER(1),
  STUNDE          NUMBER(5,2),
  CONSTRAINT HEI_EVENT_PK PRIMARY KEY (EVENT_ID),
  CONSTRAINT HEI_EVENT_SESSION_FK FOREIGN KEY (SESSION_ID) REFERENCES HEI_SESSION (SESSION_ID) ON DELETE CASCADE
)
/

-- Kommentare

COMMENT ON TABLE HEI_SOURCE IS 'Quellen: wer sagt was, mit Kernaussage, Massen und Beleg (nach SEM_SOURCE)'
/

COMMENT ON TABLE HEI_STAGE IS 'Die vier Zeitstufen: 1619, nach 1689, nach 1693, nach 1764'
/

COMMENT ON TABLE HEI_BUILDING IS 'Bauwerke mit Rolle, Detailstufe, Zeitstufen und Lage (lokal in Metern und als Punkt in WGS84)'
/

COMMENT ON TABLE HEI_CHRONIK IS 'Geschichtliche Ereignisse zum Schloss, je Zeitstufe, mit Quelle'
/

COMMENT ON TABLE HEI_VIEW IS 'Blickpunkte: Drehpunkt, Hoehe ueber dem Boden, Gier, Nick und Abstand der Orbit-Kamera'
/

COMMENT ON TABLE HEI_CLIP IS 'Fahrten (Kamera, im Programm berechnet) und das Drehbuch; hier nur der Katalog'
/

COMMENT ON TABLE HEI_SHOT IS 'Szenen des Drehbuchs: Tageszeit von bis, Nebel, Dunst'
/

COMMENT ON TABLE HEI_PANEL IS 'Tafeln einer Szene: Zeitfenster in Sekunden, Kopf, Text, Quelle'
/

COMMENT ON TABLE HEI_SESSION IS 'Eine Zeile je Programmstart: Rechner, Fenster, Dauer, Bilder pro Sekunde'
/

COMMENT ON TABLE HEI_STATE IS 'Zustand des Programms (Kamera, Zeit, Wetter, Schalter): AUTO beim Beenden, MANUELL von Hand gemerkt'
/

COMMENT ON TABLE HEI_EVENT IS 'Protokoll einer Sitzung: Start, Ende, Fehler, Fahrten, Zeitstufen, Einrichter'
/
