-- ============================================================================
-- Heidelberger Schloss, Phase 10: Folgen, Trigger, Indizes, Geometrie-Metadaten
-- Folge <TABELLE>_SEQ und Trigger <TABELLE>_BI vergeben die ID, wie in deinen anderen Projekten.
-- ============================================================================

-- Folgen

CREATE SEQUENCE HEI_SOURCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_STAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_BUILDING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_CHRONIK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_VIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_CLIP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_SHOT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_PANEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_STATE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE SEQUENCE HEI_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/

-- Trigger

CREATE OR REPLACE TRIGGER HEI_SOURCE_BI
BEFORE INSERT ON HEI_SOURCE
FOR EACH ROW
WHEN (NEW.SOURCE_ID IS NULL)
BEGIN
  :NEW.SOURCE_ID := HEI_SOURCE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_STAGE_BI
BEFORE INSERT ON HEI_STAGE
FOR EACH ROW
WHEN (NEW.STAGE_ID IS NULL)
BEGIN
  :NEW.STAGE_ID := HEI_STAGE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_BUILDING_BI
BEFORE INSERT ON HEI_BUILDING
FOR EACH ROW
WHEN (NEW.BUILDING_ID IS NULL)
BEGIN
  :NEW.BUILDING_ID := HEI_BUILDING_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_CHRONIK_BI
BEFORE INSERT ON HEI_CHRONIK
FOR EACH ROW
WHEN (NEW.CHRONIK_ID IS NULL)
BEGIN
  :NEW.CHRONIK_ID := HEI_CHRONIK_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_VIEW_BI
BEFORE INSERT ON HEI_VIEW
FOR EACH ROW
WHEN (NEW.VIEW_ID IS NULL)
BEGIN
  :NEW.VIEW_ID := HEI_VIEW_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_CLIP_BI
BEFORE INSERT ON HEI_CLIP
FOR EACH ROW
WHEN (NEW.CLIP_ID IS NULL)
BEGIN
  :NEW.CLIP_ID := HEI_CLIP_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_SHOT_BI
BEFORE INSERT ON HEI_SHOT
FOR EACH ROW
WHEN (NEW.SHOT_ID IS NULL)
BEGIN
  :NEW.SHOT_ID := HEI_SHOT_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_PANEL_BI
BEFORE INSERT ON HEI_PANEL
FOR EACH ROW
WHEN (NEW.PANEL_ID IS NULL)
BEGIN
  :NEW.PANEL_ID := HEI_PANEL_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_SESSION_BI
BEFORE INSERT ON HEI_SESSION
FOR EACH ROW
WHEN (NEW.SESSION_ID IS NULL)
BEGIN
  :NEW.SESSION_ID := HEI_SESSION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_STATE_BI
BEFORE INSERT ON HEI_STATE
FOR EACH ROW
WHEN (NEW.STATE_ID IS NULL)
BEGIN
  :NEW.STATE_ID := HEI_STATE_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER HEI_EVENT_BI
BEFORE INSERT ON HEI_EVENT
FOR EACH ROW
WHEN (NEW.EVENT_ID IS NULL)
BEGIN
  :NEW.EVENT_ID := HEI_EVENT_SEQ.NEXTVAL;
END;
/

-- Indizes auf Fremdschluesseln und Abfragen

CREATE INDEX HEI_STAGE_SOURCE_IX ON HEI_STAGE (SOURCE_ID)
/

CREATE INDEX HEI_BUILDING_SOURCE_IX ON HEI_BUILDING (SOURCE_ID)
/

CREATE INDEX HEI_CHRONIK_STAGE_IX ON HEI_CHRONIK (STAGE_ID)
/

CREATE INDEX HEI_CHRONIK_SOURCE_IX ON HEI_CHRONIK (SOURCE_ID)
/

CREATE INDEX HEI_SHOT_SOURCE_IX ON HEI_SHOT (SOURCE_ID)
/

CREATE INDEX HEI_PANEL_SOURCE_IX ON HEI_PANEL (SOURCE_ID)
/

CREATE INDEX HEI_STATE_SESSION_IX ON HEI_STATE (SESSION_ID)
/

CREATE INDEX HEI_STATE_ART_IX ON HEI_STATE (ART, GESPEICHERT)
/

CREATE INDEX HEI_EVENT_SESSION_IX ON HEI_EVENT (SESSION_ID, ZEIT)
/

CREATE INDEX HEI_SESSION_START_IX ON HEI_SESSION (GESTARTET)
/

-- Lage der Bauwerke: Metadaten (WGS84, SRID 8307) und raeumlicher Index
BEGIN
  INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
  SELECT 'HEI_BUILDING', 'GEOM',
         SDO_DIM_ARRAY(SDO_DIM_ELEMENT('Longitude', -180, 180, 0.05),
                       SDO_DIM_ELEMENT('Latitude', -90, 90, 0.05)),
         8307
    FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM USER_SDO_GEOM_METADATA
                      WHERE TABLE_NAME = 'HEI_BUILDING' AND COLUMN_NAME = 'GEOM');
  COMMIT;
END;
/

CREATE INDEX HEI_BUILDING_SX ON HEI_BUILDING (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/
