-- ============================================================================
-- Heidelberger Schloss, Phase 10: Grunddaten der HEI_-Tabellen (erzeugt von tools.SeedGen, nicht von Hand aendern)
-- Jede Anweisung fuegt eine Zeile nur ein, wenn es sie noch nicht gibt; Aenderungen in der Datenbank bleiben stehen.
-- Quellen, Zeitstufen, Chronik, Bauwerke (mit Lage als SDO_GEOMETRY, SRID 8307), Blickpunkte, Fahrten, Drehbuch mit Tafeln.
-- ============================================================================

SET DEFINE OFF

-- ERWARTET HEI_SOURCE=8
-- ERWARTET HEI_STAGE=4
-- ERWARTET HEI_CHRONIK=13
-- ERWARTET HEI_BUILDING=32
-- ERWARTET HEI_VIEW=28
-- ERWARTET HEI_CLIP=13
-- ERWARTET HEI_SHOT=12
-- ERWARTET HEI_PANEL=27

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'WIKI_SCHLOSS', 'Wikipedia', NULL, 'Heidelberger Schloss (deutsch) und Heidelberg Castle (englisch)', NULL, 'de, en', 'Online-Enzyklopädie', NULL, 'SCHLOSS', 'Baugeschichte: Ruprechtsbau um 1400 (Wikipedia nennt ca. 1430), Ottheinrichsbau ab 1556, Friedrichsbau 1601 bis 1607 (Architekt Johannes Schoch), Englischer Bau 1612/13. Brandlegung am 2. März 1689, Sprengung am 6. September 1693, Blitzschlag am 24. Juni 1764. Lage auf der Jettenbühl-Terrasse am Nordhang des Königstuhls, rund 80 m über der Altstadt.', NULL, 'Die Staatlichen Schlösser und Gärten nennen für die Zerstörung 1688 statt 1689.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'SSG_BW', 'Staatliche Schlösser und Gärten Baden-Württemberg', NULL, 'Schloss Heidelberg: Zeitreise und Geschichte (schloss-heidelberg.de)', NULL, 'de', 'Amtliche Darstellung des Landes', NULL, 'SCHLOSS', 'Das Schloss auf dem Jettenbühl wird 1303 als Sitz der Pfalzgrafen erstmals fassbar. Ruprechtsbau um 1400, Hortus Palatinus ab 1616, Gläserner Saalbau unter Friedrich II. 1544 bis 1556, Zerstörung 1688, doppelter Blitzeinschlag 1764.', 'Fass von 1591: 130 000 Liter', 'Wikipedia nennt für den Ruprechtsbau ca. 1430, für den Beginn des Hortus Juli 1614 (englisch) oder 1616 (deutsch).' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'SSG_BW')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'WIKI_HORTUS', 'Wikipedia', NULL, 'Hortus Palatinus (deutsch und englisch)', NULL, 'de, en', 'Online-Enzyklopädie', NULL, 'HORTUS', 'Salomon de Caus legte den Garten ab Juli 1614 (englisch) oder 1616 (deutsch) an, rund 5 ha groß, L-förmig um das Schloss. Der Garten wurde nie fertig: Die Arbeit ruhte ab Ende 1619, im Dreißigjährigen Krieg wurde er zerstört. Das Stichwerk von 1620 zeigt den Plan.', 'Rund 5 ha; Obere Terrasse 8,5 m breit und 2,5 m höher als die mittlere; Bogenbau 20 m hoch; Pomeranzenbäume etwa 60 Jahre alt', 'Die Quellen nennen als Beginn Juli 1614 oder 1616.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'WIKI_FASS', 'Wikipedia', NULL, 'Großes Fass des Heidelberger Schlosses', NULL, 'de', 'Online-Enzyklopädie', NULL, 'FASSBAU', 'Pfalzgraf Johann Casimir ließ das Fass 1589 bis 1591 von Baumeister Michael Werner aus Landau bauen; es fasste rund 127 000 Liter. Im Dreißigjährigen Krieg wurde es zerstört. Maße sind nicht überliefert; ein Tanzboden ist erst vom Fass von 1664 überliefert.', 'Rund 127 000 Liter', 'zum.de nennt 128 000 Liter, die Staatlichen Schlösser und Gärten 130 000 Liter.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'WIKI_FASS')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'ZUM', 'zum.de', NULL, 'Das Heidelberger Fass', NULL, 'de', 'Lehrmaterial im Netz', NULL, 'FASSBAU', 'Das Große Fass von 1591 fasste 128 000 Liter.', '128 000 Liter', 'Wikipedia nennt rund 127 000 Liter.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'ZUM')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'DECAUS_1620', 'Salomon de Caus', NULL, 'Hortus Palatinus, Stichwerk von 1620', NULL, 'französisch, lateinisch', 'Gedruckte Stiche, ein Jahr nach dem Stand der Szene', 1, 'HORTUS', 'Das Stichwerk von 1620 zeigt den Plan des Gartens, nicht den Stand des Gebauten. Höhen der Wasserstrahlen nennt de Caus nicht.', NULL, 'Der Garten wurde nie fertig; was die Stiche zeigen, ist der Plan.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'DECAUS_1620')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'EML_2003', 'European Media Laboratory, Heidelberg', NULL, 'Digitale Rekonstruktion der Gärten (2003)', NULL, 'de', 'Frühere Rekonstruktion, dient hier nur als Vorarbeit', NULL, 'HORTUS', 'Eine digitale Rekonstruktion des Hortus Palatinus entstand 2003 am European Media Laboratory in Heidelberg.', NULL, NULL FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'EML_2003')
/

INSERT INTO HEI_SOURCE (CODE, AUTOR, LEBENSZEIT, WERK, STELLE, SPRACHE, UEBERLIEFERUNG, ABSTAND_JAHRE, BEZUG, KERNAUSSAGE, MASSE, BELEG)
SELECT 'MODELL', 'Rekonstruktion (Modell)', NULL, 'Annahmen und Modelle dieses Programms', NULL, 'de', 'Eigenleistung', NULL, NULL, 'Wo keine Quelle Maße oder Lage nennt, gilt eine Annahme der Rekonstruktion: Lage und Maße der Bauten zueinander (geschätzt, einige Meter), Wappen, Hofstaat, Kleidung, Wege, Nebeltage, Wetter, Tageslauf, Strahlhöhen der Fontänen, Quelle und Leitungen des Wasserwegs, Höhe der Ruinenmauern.', NULL, 'Im Programm als „Annahme der Rekonstruktion“ oder „Modell“ gekennzeichnet.' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SOURCE WHERE CODE = 'MODELL')
/

INSERT INTO HEI_STAGE (NR, JAHR, DATUM, NAME, KURZ, BESCHREIBUNG, SOURCE_ID)
SELECT 0, 1619, NULL, '1619 (Blütezeit)', 'Schloss und Hortus Palatinus im Herbst 1619, vor jeder Zerstörung', 'Prunkbauten voll, übrige Bauten mittel, Türme einfach; der Hortus ist nach de Caus gebaut, was nur geplant war, lässt sich bläulich tönen. Im Herbst 1619 wird Friedrich V. zum König von Böhmen gewählt, die Gartenarbeiten stehen danach still.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_STAGE WHERE NR = 0)
/

INSERT INTO HEI_STAGE (NR, JAHR, DATUM, NAME, KURZ, BESCHREIBUNG, SOURCE_ID)
SELECT 1, 1689, DATE '1689-03-02', 'Nach dem Brand 1689', 'Brandlegung im Pfälzischen Erbfolgekrieg: Dächer, Decken und Einbauten sind verloren', 'Mauern ohne Dächer, Decken, Einbauten und Glas, mit gebrochener Krone. Wikipedia nennt den 2. März 1689, die Staatlichen Schlösser 1688. Wie hoch jede Mauer stehen blieb, ist Annahme der Rekonstruktion.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_STAGE WHERE NR = 1)
/

INSERT INTO HEI_STAGE (NR, JAHR, DATUM, NAME, KURZ, BESCHREIBUNG, SOURCE_ID)
SELECT 2, 1693, DATE '1693-09-06', 'Nach der Sprengung 1693', 'Französische Pioniere sprengen Türme, darunter den Krautturm', 'Türme und Mauern weiter gebrochen; der Notdach-Zustand des Ottheinrichsbaus ist Annahme der Rekonstruktion.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_STAGE WHERE NR = 2)
/

INSERT INTO HEI_STAGE (NR, JAHR, DATUM, NAME, KURZ, BESCHREIBUNG, SOURCE_ID)
SELECT 3, 1764, DATE '1764-06-24', 'Nach dem Blitz 1764 (heute)', 'Blitzschlag und Brände; der Wiederaufbau wird aufgegeben, es bleibt die Ruine von heute', 'Der Zustand von heute als Ruine. Der Friedrichsbau wurde 1897 bis 1900 als einziger Bau wiederhergestellt; das Modell zeigt auch ihn als Ruine.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_STAGE WHERE NR = 3)
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1303, NULL, 'Sitz der Pfalzgrafen', 'Das Schloss auf dem Jettenbühl wird als Sitz der Pfalzgrafen erstmals fassbar.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'SSG_BW') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1303 AND TITEL = 'Sitz der Pfalzgrafen')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1400, NULL, 'Ruprechtsbau', 'Der Ruprechtsbau entsteht unter Ruprecht III. um 1400 (Wikipedia nennt ca. 1430).', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1400 AND TITEL = 'Ruprechtsbau')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1510, NULL, 'Bauten Ludwigs V.', '1510 bis 1541: Frauenzimmerbau, Bibliotheksbau, Ludwigsbau (1524), Dicker Turm (1533) und Torturm (1531 bis 1541).', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1510 AND TITEL = 'Bauten Ludwigs V.')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1556, NULL, 'Ottheinrichsbau', 'Ab 1556 entsteht der Ottheinrichsbau, das Hauptwerk der Renaissance am Schloss.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1556 AND TITEL = 'Ottheinrichsbau')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1589, NULL, 'Fassbau und Großes Fass', '1589 bis 1592 wird der Fassbau für das Große Fass von 1591 gebaut, damals rund 127 000 Liter.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_FASS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1589 AND TITEL = 'Fassbau und Großes Fass')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1601, NULL, 'Friedrichsbau', '1601 bis 1607 baut Friedrich IV. den Friedrichsbau, Architekt Johannes Schoch, mit der ersten Stadtfassade.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1601 AND TITEL = 'Friedrichsbau')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1612, NULL, 'Englischer Bau', '1612/13 lässt Friedrich V. den Englischen Bau errichten, benannt nach seiner Frau Elisabeth Stuart.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1612 AND TITEL = 'Englischer Bau')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1614, NULL, 'Hortus Palatinus', 'Salomon de Caus legt den Hortus Palatinus an; die Quellen nennen als Beginn Juli 1614 oder 1616. Ende 1619 bleibt die Arbeit liegen.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1614 AND TITEL = 'Hortus Palatinus')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 0), 1619, NULL, 'König von Böhmen', 'Im Herbst 1619 wird Friedrich V. zum König von Böhmen gewählt; die Arbeit am Garten ruht danach.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1619 AND TITEL = 'König von Böhmen')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 1), 1689, DATE '1689-03-02', 'Brandlegung', 'Brandlegung im Pfälzischen Erbfolgekrieg am 2. März 1689 (Staatliche Schlösser und Gärten nennen 1688).', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1689 AND TITEL = 'Brandlegung')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 2), 1693, DATE '1693-09-06', 'Sprengung der Türme', 'Französische Pioniere sprengen Türme, darunter den Krautturm.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1693 AND TITEL = 'Sprengung der Türme')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 3), 1764, DATE '1764-06-24', 'Blitzschlag', 'Ein Blitzschlag löst Brände aus; der Wiederaufbau wird aufgegeben.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1764 AND TITEL = 'Blitzschlag')
/

INSERT INTO HEI_CHRONIK (STAGE_ID, JAHR, DATUM, TITEL, TEXT, SOURCE_ID)
SELECT (SELECT STAGE_ID FROM HEI_STAGE WHERE NR = 3), 1897, NULL, 'Friedrichsbau wiederhergestellt', '1897 bis 1900 wird der Friedrichsbau als einziger Bau wiederhergestellt.', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CHRONIK WHERE JAHR = 1897 AND TITEL = 'Friedrichsbau wiederhergestellt')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'SCHLOSSHOF', 'Schlosshof', NULL, 'HOF', 'MITTEL', 15, 'Ursprung des Modells (0, 0), Hofniveau y = 0, Pflaster; Lage der Bauten zueinander aus Plänen geschätzt.', 0, 0, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71530000, 49.40670000, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'SCHLOSSHOF')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'TORTURM', 'Torturm', NULL, 'TURM', 'VOLL', 15, 'Ludwig V., 1531 bis 1541. 52 m hoch, Zugang zum Schloss. Die Barockhaube stammt von etwa 1716, die Dachform von 1619 ist als Pyramide angenommen.', -52, 2, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71458211, 49.40668203, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'TORTURM')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'TORBRUECKE', 'Torbrücke', NULL, 'BAU', 'MITTEL', 15, 'Brücke über den Graben vor dem Torturm; Form und Lage sind Annahmen der Rekonstruktion.', -78, 2, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71422316, 49.40668203, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'TORBRUECKE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'DICKER_TURM', 'Dicker Turm', NULL, 'TURM', 'VOLL', 15, 'Ludwig V., 1533. 40 m hoch, 7 m Mauerstärke.', 60, -44, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71612834, 49.40709526, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'DICKER_TURM')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'OTTHEINRICHSBAU', 'Ottheinrichsbau', NULL, 'BAU', 'VOLL', 15, 'Ottheinrich, ab 1556. Manierismus, Bildhauer A. Colin; Architekt unbekannt.', -17, -29, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71506530, 49.40696051, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'OTTHEINRICHSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'FRIEDRICHSBAU', 'Friedrichsbau', NULL, 'BAU', 'VOLL', 15, 'Friedrich IV., 1601 bis 1607. Architekt Johannes Schoch, Stadtfassade; 1897 bis 1900 als einziger Bau wiederhergestellt.', 31, -31, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71572797, 49.40697848, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'FRIEDRICHSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'SAALBAU', 'Gläserner Saalbau', NULL, 'BAU', 'VOLL', 15, 'Friedrich II., 16. Jahrhundert (1544 bis 1556). Spiegelsaal mit venezianischem Glas; im Modell innen hohl und ebenerdig.', 8, -27, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71541044, 49.40694254, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'SSG_BW') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'SAALBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'FASSBAU', 'Fassbau', NULL, 'BAU', 'VOLL', 15, 'Johann Casimir, 1589 bis 1592. Fass von 1591, rund 127 000 Liter (Staatliche Schlösser: 130 000); im Modell innen hohl.', 43, 19, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71589364, 49.40652932, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_FASS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'FASSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'ENGLISCHER_BAU', 'Englischer Bau', NULL, 'BAU', 'MITTEL', 15, 'Friedrich V., 1612/13. Architekt vermutlich Inigo Jones.', -23, 31, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71498247, 49.40642152, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'ENGLISCHER_BAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'RUPRECHTSBAU', 'Ruprechtsbau', NULL, 'BAU', 'MITTEL', 15, 'Ruprecht III., um 1400 (Wikipedia: ca. 1430). Älteste erhaltene Teile.', 41, -9, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71586603, 49.40678085, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'RUPRECHTSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'FRAUENZIMMERBAU', 'Frauenzimmerbau', NULL, 'BAU', 'MITTEL', 15, 'Ludwig V., um 1510. Hofstube 34,65 m × 16,70 m.', 13, 30, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71547947, 49.40643051, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'FRAUENZIMMERBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'BIBLIOTHEKSBAU', 'Bibliotheksbau', NULL, 'BAU', 'MITTEL', 15, 'Ludwig V., um 1520. Mauern im Erdgeschoss 3 m dick.', -39, -13, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71476158, 49.40681678, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'BIBLIOTHEKSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'LUDWIGSBAU', 'Ludwigsbau', NULL, 'BAU', 'MITTEL', 15, 'Ludwig V., 1524. Mauern im Erdgeschoss 3 m dick.', -39, 14, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71476158, 49.40657424, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'LUDWIGSBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'KRAUTTURM', 'Krautturm', NULL, 'TURM', 'MITTEL', 15, '15. Jahrhundert. Pulvermagazin, 1693 gesprengt.', 68, 48, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71623878, 49.40626881, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'KRAUTTURM')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'GLOCKENTURM', 'Glockenturm', NULL, 'TURM', 'EINFACH', 15, 'Um 1490. Wehrturm am Rand der Anlage.', -58, -44, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71449927, 49.40709526, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'GLOCKENTURM')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'APOTHEKERTURM', 'Apothekerturm', NULL, 'TURM', 'EINFACH', 15, 'Um 1490. Wehrturm am Rand der Anlage.', -58, 36, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71449927, 49.40637661, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'APOTHEKERTURM')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'BRUNNENHALLE', 'Brunnenhalle', NULL, 'BAU', 'MITTEL', 15, 'Ludwig V. Ziehbrunnen, rund 16 m tief, seit 1508; vier Monolithe.', -21, 5, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71501008, 49.40665508, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'BRUNNENHALLE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'ELISABETHENTOR', 'Elisabethentor', NULL, 'HORTUS', 'MITTEL', 15, 'Friedrich V., vor 1620. Am Stückgarten, Eingang zum Hortus.', -104, 8, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71386422, 49.40662814, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'ELISABETHENTOR')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'HORTUS_HAUPT', 'Hortus Palatinus, Hauptterrasse', NULL, 'HORTUS', 'MITTEL', 15, 'Salomon de Caus, ab 1614 oder 1616. Hauptterrasse mit Knotenfeldern aus Thymian, Rosmarin, Lavendel und Salbei, dazwischen farbige Kiesel; rund 5 ha Gesamtfläche, L-förmig um das Schloss.', -70, 102, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40578372, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'HORTUS_HAUPT')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'PYRAMIDENTREPPE', 'Pyramidentreppe', NULL, 'HORTUS', 'MITTEL', 15, 'Nach de Caus nur geplant, nie gebaut; im Modell bläulich getönt (Schalter „Geplantes blau tönen“).', -70, 116, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40565796, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'DECAUS_1620') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'PYRAMIDENTREPPE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'BOGENBAU', 'Scheffelterrasse und Bogenbau', NULL, 'HORTUS', 'MITTEL', 15, 'Die Scheffelterrasse ruhte auf einem 20 m hohen Bogenbau mit Nischen.', -132, 102, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71347766, 49.40578372, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'BOGENBAU')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'GROSSE_GROTTE', 'Große Grotte', NULL, 'HORTUS', 'VOLL', 15, 'Vier Räume. Im ersten fließt Wasser kaskadenartig in ein Becken mit Springbrunnen, im zweiten steht ein Steintisch mit Wassermechanik, dazu kommt die Wasserorgel nach Vitruv. Im Modell begehbar.', -70, 90, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40589152, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'GROSSE_GROTTE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'KLEINE_GROTTE', 'Kleine Grotte', NULL, 'HORTUS', 'VOLL', 15, 'Liegt neben der Großen Grotte; im Modell begehbar, mit Überlauf und Maul-Bogen.', -106, 90, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71383660, 49.40589152, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'KLEINE_GROTTE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'SAEULENBRUNNEN', 'Säulenbrunnen', NULL, 'WASSER', 'VOLL', 15, 'Säulenbrunnen im Zentrum eines Knotenfeldes.', -118, 111, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71367094, 49.40570287, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'SAEULENBRUNNEN')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'ACHTECKBECKEN', 'Achteckbecken', NULL, 'WASSER', 'VOLL', 15, 'Achteckiges Bassin mit Fratzengesichtern aus Metall. Nach de Caus nur geplant, nie fertiggestellt; im Modell bläulich getönt.', -70, 102, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40578372, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'ACHTECKBECKEN')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'RHENUSBECKEN', 'Rhenusbecken', NULL, 'WASSER', 'VOLL', 15, 'Becken mit dem Rhenus vor der Großen Grotte. Nach de Caus nur geplant, nie fertiggestellt; im Modell bläulich getönt.', -70, 79, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40599033, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'RHENUSBECKEN')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'POMERANZEN', 'Pomeranzenbäume in Kästen', NULL, 'HORTUS', 'MITTEL', 15, 'Pomeranzenbäume, rund 60 Jahre alt, in hochsitzenden Erdkästen (nach der englischen Quelle dreißig Stück).', -70, 117.4, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40564538, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'POMERANZEN')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'WASSERORGEL', 'Wasserorgel', NULL, 'WASSER', 'VOLL', 15, 'Wasserorgel nach Vitruv in der Großen Grotte. Melodie (D-dorisch) und Klang sind Eigenleistung der Rekonstruktion.', -70, 105.8, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71433361, 49.40574959, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'WASSERORGEL')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'BRUNNENSTUBE', 'Brunnenstube des Wasserwegs', NULL, 'WASSER', 'MITTEL', 15, 'Quelle am Nordhang; Lage und Leitungen sind Annahmen nach de Caus.', -94, 172, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71400227, 49.40515490, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'BRUNNENSTUBE')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'MAUERFALL', 'Mauerfall und Trog', NULL, 'WASSER', 'MITTEL', 15, 'Station des Wasserwegs; Annahme der Rekonstruktion.', -94, 117.7, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71400227, 49.40564269, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'MAUERFALL')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'WASSERSPEIER', 'Wasserspeier an der Westmauer', NULL, 'WASSER', 'MITTEL', 15, 'Abfluss des Wasserwegs; Annahme der Rekonstruktion.', -132, 79, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71347766, 49.40599033, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'WASSERSPEIER')
/

INSERT INTO HEI_BUILDING (CODE, NAME, NAME_HISTORISCH, BEZUG, DETAIL, STUFEN, ROLLE, X_M, Z_M, GEOM, SOURCE_ID)
SELECT 'ABFLUSSBACH', 'Abflussbach', NULL, 'WASSER', 'MITTEL', 15, 'Der Abfluss geht ins Friesentälchen und von dort zum Neckar; der Verlauf ist Annahme der Rekonstruktion.', -136.5, 79, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(8.71341553, 49.40599033, NULL), NULL, NULL), (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_BUILDING WHERE CODE = 'ABFLUSSBACH')
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 0, 'Übersicht über das Tal', 'Phase 1: Tal und Stadt', -250, -250, 20, 226, 15, 2300, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 0)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 1, 'Schloss vom Neckar', 'Phase 1: Tal und Stadt', 0, 0, 14, 212, 9, 430, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 1)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 2, 'Schlosshof', 'Phase 1: Tal und Stadt', 0, 0, 6, 160, 14, 95, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 2)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 3, 'Alte Brücke', 'Phase 1: Tal und Stadt', -440, -650, 4, 180, 9, 230, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 3)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 4, 'Marktplatz und Heiliggeistkirche', 'Phase 1: Tal und Stadt', -545, -318, 22, 150, 24, 170, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 4)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 5, 'Königstuhl', 'Phase 1: Tal und Stadt', -200, -300, 0, 38, 14, 1700, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 5)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 6, 'Heiligenberg', 'Phase 1: Tal und Stadt', -100, -200, 20, 194, 6, 2300, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 6)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 7, 'Neckartal von Osten', 'Phase 1: Tal und Stadt', -300, -520, 10, 95, 7, 1500, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 7)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 8, 'Hof zum Friedrichsbau', 'Phase 3 und 4: Schloss und Hortus', -0.4, 6.9, 3.78, 320, -9.5, 12, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 8)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 9, 'Hof zum Ottheinrichsbau', 'Phase 3 und 4: Schloss und Hortus', 12, 3.2, 3.56, 42, -8.4, 12, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 9)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 10, 'Schloss von oben', 'Phase 3 und 4: Schloss und Hortus', -167.2, 203.2, 130.97, 320, 28.4, 40, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 10)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 11, 'Hortus Hauptterrasse', 'Phase 3 und 4: Schloss und Hortus', -23.8, 113.9, 3.19, 78, -1.1, 10, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 11)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 12, 'Große Grotte', 'Phase 3 und 4: Schloss und Hortus', -70, 76, 1.29, 180, 5.2, 10, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 12)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 13, 'Hortus von oben', 'Phase 3 und 4: Schloss und Hortus', -3.8, 164.9, 59.91, 43, 30.1, 40, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 13)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 14, 'Gläserner Saalbau innen', 'Phase 3 und 4: Schloss und Hortus', 6.5, -26.7, 2.08, 236, -3.6, 6, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 14)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 15, 'Achteckbecken', 'Phase 5: Brunnen', -75.9, 106.2, 2.74, 306, -6, 10, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 15)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 16, 'Säulenbrunnen', 'Phase 5: Brunnen', -116.8, 112.4, 5.65, 41, -22.4, 8, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 16)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 17, 'Rhenusbecken', 'Phase 5: Brunnen', -70, 78.8, 2.6, 193, 0, 9, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 17)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 18, 'Kaskade der Großen Grotte', 'Phase 5: Brunnen', -70, 93, 1.37, 180, 3.1, 6, 'J' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 18)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 19, 'Schloss über dem Nebelmeer', 'Phase 6: Dampf und Licht', 0, 0, 10, 235, 4.2, 540, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 19)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 20, 'Schlosshof bei Nacht', 'Phase 6: Dampf und Licht', 25, 0, 3, 280.3, -1.3, 56, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 20)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 21, 'Hortus bei Nacht', 'Phase 6: Dampf und Licht', -80, 102, 2.4, 51.3, -1, 38, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 21)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 22, 'Altstadt im Morgenrauch', 'Phase 6: Dampf und Licht', -470, -320, 15, 258.7, 27, 55, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 22)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 23, 'Regenbogen über dem Schlossberg', 'Phase 6: Dampf und Licht', -30, 60, 30, 270, 2, 30, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 23)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 24, 'Abendrot über der Rheinebene', 'Phase 6: Dampf und Licht', -49.4, 97.3, 5.5, 62.1, -3.6, 40, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 24)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 25, 'Das Große Fass im Fassbau', 'Phase 8: Räume und Leben', 43.4, 17, 3.3, 270, -12, 7, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 25)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 26, 'Saal bei Kerzenlicht', 'Phase 8: Räume und Leben', 8, -30, 2.6, 0, -4, 6.5, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 26)
/

INSERT INTO HEI_VIEW (NR, NAME, NOTIZ, DREHPUNKT_X, DREHPUNKT_Z, HOEHE_UEBER_BODEN, GIER_GRAD, NICK_GRAD, ABSTAND_M, INNEN)
SELECT 27, 'Hof mit Hofstaat', 'Phase 8: Räume und Leben', 10, 2, 1.5, 300, -3, 16, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_VIEW WHERE NR = 27)
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_01', 'FAHRT', 0, 1, 'Rundumblick im Schlosshof', 'Ein voller Kreis aus dem Hof, die Fassaden ziehen vorbei.', 54 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_01')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_02', 'FAHRT', 0, 2, 'Rundumblick vom Hortus', 'Ein voller Kreis von der Hauptterrasse: Schloss, Garten, Rheinebene.', 54 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_02')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_03', 'FAHRT', 0, 3, 'Rundumblick vom Königstuhl', 'Ein voller Kreis vom Gipfel, 45 m über dem Boden, damit die Baumkronen den Blick freigeben: Tal, Stadt, Schloss, Ebene.', 60 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_03')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_04', 'FAHRT', 0, 4, 'Anflug auf das Schloss', 'Vom Neckar über den Torturm hinab in den Hof.', 36 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_04')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_05', 'FAHRT', 0, 5, 'Orbit um das Schloss', 'Ein hoher Kreis um die ganze Anlage.', 70 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_05')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_06', 'FAHRT', 0, 6, 'Überflug des Hortus', 'Tief über die Terrassen, an Becken und Säulenbrunnen vorbei.', 24.56 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_06')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_07', 'FAHRT', 0, 7, 'Vom Hof in den Fassbau', 'Ohne Schnitt vom Hof durch die Tür des Fassbaus, am Großen Fass entlang und um das Fass herum.', 30.98 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_07')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_08', 'FAHRT', 0, 8, 'Rundgang durch Tor und Hof', 'Zu Fuß von der Torbrücke durch den Torturm, über den Hof bis in den Gläsernen Saalbau.', 49.7 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_08')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_09', 'FAHRT', 0, 9, 'Dem Wasser folgen', 'Von der Quelle am Hang über die Terrassen, durch Leitung und Grotte, über die Westmauer und den Bach bis zum Neckar (mit Perlen).', 143.37 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_09')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_10', 'FAHRT', 0, 10, 'Zoom zum Wappen am Ottheinrichsbau', 'Aus dem Hof (oder von der Brücke) bis vor das kurpfälzische Wappen.', 16.5 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_10')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_11', 'FAHRT', 0, 11, 'Zoom zum Wappen am Friedrichsbau', 'Aus dem Hof (oder von der Brücke) bis vor das kurpfälzische Wappen.', 16.5 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_11')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'FAHRT_12', 'FAHRT', 0, 12, 'Zoom zum Wappen am Torturm', 'Aus dem Hof (oder von der Brücke) bis vor das kurpfälzische Wappen.', 16.5 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'FAHRT_12')
/

INSERT INTO HEI_CLIP (CODE, ART, STUFE, NR, NAME, INFO, DAUER_S)
SELECT 'DREHBUCH_JETTENBUEHL', 'DREHBUCH', 0, 1, 'Ein Tag auf dem Jettenbühl', 'Zwölf Szenen vom Sonnenaufgang bis zur Nacht mit Tafeln und Quellen; Tag, Wetter und Nebel sind ein Modell.', 444.25 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL')
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 1, 'Vor Sonnenaufgang', 6.6, 7.9, 'J', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1), 2, 12, 'Ein Tag auf dem Jettenbühl', 'Das Heidelberger Schloss um 1619, als Rekonstruktion. Der Tag ist ein Modell: Sonnenstand, Nebel und Wetter folgen dem Programm, nicht einer Überlieferung.', 'Rekonstruktion (Modell)', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1) AND VON_S = 2)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1), 18, 29, 'Lage', 'Das Schloss steht auf der Jettenbühl-Terrasse am Nordhang des Königstuhls, rund 80 m über der Altstadt.', 'Wikipedia: Heidelberger Schloss, Heidelberg Castle', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1) AND VON_S = 18)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1), 35, 46, 'Talnebel', 'Nebel baut sich nachts im Neckartal auf und wird von der Sonne aufgezehrt. Welche Tage Nebel haben, legt das Programm als Modell fest.', 'Modell der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 1) AND VON_S = 35)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 2, 'Sonnenaufgang', 7.9, 9, 'J', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 2)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 2), 5, 16, 'Roter Sandstein', 'Das Schloss besteht aus rotem Neckartäler Sandstein, dem Buntsandstein. Die Mauern leuchten, sobald die Sonne über den Berg kommt.', 'Wikipedia: Heidelberger Schloss', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 2) AND VON_S = 5)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 2), 24, 38, 'Der Nebel zieht ab', 'Je höher die Sonne steigt, desto tiefer sinkt die Nebelbank und desto größer werden die Lücken.', 'Modell der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 2) AND VON_S = 24)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 3, 'Der Torturm', 9, 10, 'J', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 3)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 3), 10, 21, 'Torturm', 'Ludwig V. ließ ihn von 1531 bis 1541 bauen; er ist 52 m hoch und führt in das Schloss. Die Barockhaube stammt von etwa 1716, die Dachform von 1619 ist hier als Pyramide angenommen.', 'Wikipedia: Heidelberger Schloss', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 3) AND VON_S = 10)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 3), 25, 36, 'Der Hof', 'Um den Hof stehen Bauten aus vier Jahrhunderten: der Ruprechtsbau um 1400 (Wikipedia nennt ca. 1430), der Ottheinrichsbau ab 1556, der Friedrichsbau 1601 bis 1607.', 'Staatliche Schlösser und Gärten; Wikipedia', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'SSG_BW') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 3) AND VON_S = 25)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 4, 'Zu Fuß durch Tor und Hof', 10, 11.2, 'J', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4), 5, 13, 'Wappen am Torturm', 'Pfälzer Löwe, bayerische Rauten, Reichsapfel und Kurhut. Form, Ort und Größe der Wappen sind hier angenommen und stilisiert.', 'Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4) AND VON_S = 5)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4), 23, 35, 'Friedrichsbau', 'Gebaut 1601 bis 1607 unter Friedrich IV., Architekt Johannes Schoch. Er ist der einzige Bau, der 1897 bis 1900 wiederhergestellt wurde.', 'Wikipedia: Heidelberger Schloss', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4) AND VON_S = 23)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4), 37, 44, 'Ottheinrichsbau', 'Das Hauptwerk der Renaissance am Schloss, ab 1556. Der Bildhauer war A. Colin; der Architekt ist unbekannt.', 'Wikipedia: Heidelberger Schloss', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4) AND VON_S = 37)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4), 45, 49, 'Hinein', 'Der Weg führt in den Gläsernen Saalbau.', 'Rundgang der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 4) AND VON_S = 45)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 5, 'Mittag im Saal', 11.2, 12.5, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 5)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 5), 2, 12, 'Gläserner Saalbau', 'Ein Saal mit venezianischem Glas, unter Friedrich II. im 16. Jahrhundert. Die Säulen sind hier so gestellt, dass die Tür frei bleibt.', 'Wikipedia: Heidelberger Schloss; Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 5) AND VON_S = 2)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 5), 15, 27, 'Lichtschacht', 'Durch die hohen Fenster fallen Sonnenstrahlen auf den Marmorboden. Staubluft im Saal macht sie sichtbar; das Licht ist gerechnet, nicht gemalt.', 'Technik der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 5) AND VON_S = 15)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 6, 'Das Große Fass', 12.5, 13.3, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 6)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 6), 2, 13, 'Das Große Fass von 1591', 'Pfalzgraf Johann Casimir ließ es 1589 bis 1591 von Baumeister Michael Werner aus Landau bauen; es fasste rund 127.000 Liter (zum.de nennt 128.000). Im Dreißigjährigen Krieg wurde es zerstört. Maße sind nicht überliefert: Länge und Bauch sind hier angenommen.', 'Wikipedia: Großes Fass des Heidelberger Schlosses; zum.de; Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_FASS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 6) AND VON_S = 2)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 6), 15, 28, 'Küfer und Kerzen', 'Küfer, Leiter, Kerzen und das Wappen am Fassboden sind Annahmen der Rekonstruktion. Ein Tanzboden auf dem Fass ist erst vom Fass von 1664 überliefert und hier nicht gebaut.', 'Wikipedia: Großes Fass des Heidelberger Schlosses; Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_FASS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 6) AND VON_S = 15)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 7, 'Der Hortus Palatinus', 13.3, 14.2, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 7)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 7), 3, 13, 'Hortus Palatinus', 'Salomon de Caus legte ihn ab 1614 oder 1616 an (die Quellen sagen es verschieden), rund 5 ha groß, L-förmig um das Schloss.', 'Wikipedia: Hortus Palatinus (deutsch, englisch); Staatliche Schlösser und Gärten', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 7) AND VON_S = 3)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 7), 14, 24, 'Wasserkünste', 'Lage, Zahl und Höhe der Strahlen sind geschätzt; de Caus nennt keine Höhen. Die Fontänen laufen hier als Tropfen auf Wurfbahnen.', 'Wikipedia: Hortus Palatinus; Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 7) AND VON_S = 14)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 8, 'Das Achteckbecken', 14.2, 15, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 8)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 8), 2, 14, 'Achteckbecken', 'Ein achteckiges Bassin mit Fratzengesichtern aus Metall. Der Garten wurde nie fertig; das Stichwerk von 1620 zeigt den Plan.', 'Wikipedia: Hortus Palatinus (deutsch, englisch)', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 8) AND VON_S = 2)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 9, 'Das Schloss von oben', 15, 17.2, 'N', 0.14 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9), 4, 16, 'Bauzeiten', '1303 erstmals als Sitz fassbar · um 1400 Ruprechtsbau · 1531 bis 1541 Torturm · ab 1556 Ottheinrichsbau · 1601 bis 1607 Friedrichsbau.', 'Staatliche Schlösser und Gärten: Zeitreise; Wikipedia', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'SSG_BW') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9) AND VON_S = 4)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9), 22, 34, 'Englischer Bau', 'Friedrich V. ließ ihn 1612/13 bauen, benannt nach seiner Frau Elisabeth Stuart. Als Architekt gilt vermutlich Inigo Jones.', 'Wikipedia: Heidelberger Schloss', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9) AND VON_S = 22)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9), 42, 56, 'Herbst 1619', 'Im Herbst 1619 wird Friedrich V. zum König von Böhmen gewählt. Die Arbeit am Garten ruht danach.', 'Wikipedia: Hortus Palatinus; Staatliche Schlösser und Gärten', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 9) AND VON_S = 42)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 10, 'Abendrot', 17.2, 18.7, 'N', 0.3 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 10)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 10), 4, 16, 'Abend', 'Mit der Sonnenhöhe färbt sich das Licht; im Westen liegt die Rheinebene. Sobald die Sonne unter dem Horizont steht, gehen Fenster und Fackeln an.', 'Modell der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 10) AND VON_S = 4)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 10), 18, 30, 'Nie fertig', 'Die Arbeit am Garten ruhte ab Ende 1619; im Dreißigjährigen Krieg wurde er zerstört.', 'Wikipedia: Hortus Palatinus', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_HORTUS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 10) AND VON_S = 18)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 11, 'Kerzenlicht im Saal', 18.7, 19.7, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 11)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 11), 2, 13, 'Gläserner Saalbau am Abend', 'Friedrich II. ließ den Bau 1544 bis 1556 errichten; die Quellen nennen einen Saal im Obergeschoss mit venezianischem Spiegelglas. Hier steht der Saal ebenerdig; Kronleuchter, Kerzen, Spiegel und Möbel sind Annahmen.', 'Staatliche Schlösser und Gärten; zum.de; Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'SSG_BW') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 11) AND VON_S = 2)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 11), 14, 25, 'Hofstaat', 'Die Menschen sind Schattenrisse; Halskrause, Wams, Reifrock und Hellebarde folgen der Mode um 1619 in stark vereinfachter Form. Wer wann im Hof ist, legt das Programm fest.', 'Annahme der Rekonstruktion', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'MODELL') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 11) AND VON_S = 14)
/

INSERT INTO HEI_SHOT (CLIP_ID, NR, NAME, STUNDE_VON, STUNDE_BIS, NEBEL, DUNST)
SELECT (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL'), 12, 'Fackelnacht und Mond', 19.7, 20.6, 'N', 0.12 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 12)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 12), 3, 16, 'Was folgt', 'Brandlegung 1688 (Staatliche Schlösser) oder am 2. März 1689 (Wikipedia). 1693 sprengen französische Pioniere Türme. Am 24. Juni 1764 schlägt der Blitz ein; der Wiederaufbau wird aufgegeben.', 'Wikipedia: Heidelberger Schloss; Staatliche Schlösser und Gärten', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 12) AND VON_S = 3)
/

INSERT INTO HEI_PANEL (SHOT_ID, VON_S, BIS_S, KOPF, TEXT, QUELLE_TEXT, SOURCE_ID)
SELECT (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 12), 19, 32, 'Ende', 'Ein Tag auf dem Jettenbühl. Die Angaben sind nachgeschlagen; wo Quellen sich widersprechen, steht beides.', 'Wikipedia; Staatliche Schlösser und Gärten Baden-Württemberg', (SELECT SOURCE_ID FROM HEI_SOURCE WHERE CODE = 'WIKI_SCHLOSS') FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM HEI_PANEL WHERE SHOT_ID = (SELECT SHOT_ID FROM HEI_SHOT WHERE CLIP_ID = (SELECT CLIP_ID FROM HEI_CLIP WHERE CODE = 'DREHBUCH_JETTENBUEHL') AND NR = 12) AND VON_S = 19)
/

